version: '3.7'

services:
  #Frontend Service
  client:
    container_name: frontend-container
    build: 
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./mongodbdata:/data/db

 #Backend Service
  server:
    container_name: backend_container
    build: 
      context: ./server
    ports:
      - "8000:8000"

volumes:
  mongodbdata:
    driver: local