version: '3.7'

services:
  #Frontend Service
  client:
    container_name: frontend-container
    build: 
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
  mongo:
    container_name: mongo
    # command: mongod --auth
    image: mongo
    restart: always
    # environment:
    #   - MONGO_INITDB_DATABASE=my_db
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=example  
    volumes:
      - ./mongodbdata:/data/db
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

 #Backend Service
  server:
    container_name: backend_container
    build: 
      context: ./server
    ports:
      - "8000:8000"

volumes:
  mongodbdata:
    driver: local